#pragma once

// Auto-generated by Upways Vulkan Exporter
#include <cstdint>

namespace upways {

struct LayerDescriptor {
    uint32_t weightOffset;
    uint32_t weightSize;
    uint32_t scaleOffset;
    uint32_t scaleSize;
    uint32_t biasOffset;
    uint32_t biasSize;
    uint32_t outChannels;
    uint32_t inChannels;
};

constexpr uint32_t TOTAL_WEIGHT_BUFFER_SIZE = 524792;

// Layer: enc0_proj
inline constexpr LayerDescriptor LAYER_ENC0_PROJ = {
    .weightOffset = 0,
    .weightSize   = 4608,
    .scaleOffset  = 4608,
    .scaleSize    = 128,
    .biasOffset   = 4736,
    .biasSize     = 128,
    .outChannels  = 32,
    .inChannels   = 16
};

// Layer: enc0_res_conv1
inline constexpr LayerDescriptor LAYER_ENC0_RES_CONV1 = {
    .weightOffset = 4864,
    .weightSize   = 9216,
    .scaleOffset  = 14080,
    .scaleSize    = 128,
    .biasOffset   = 14208,
    .biasSize     = 128,
    .outChannels  = 32,
    .inChannels   = 32
};

// Layer: enc0_res_conv2
inline constexpr LayerDescriptor LAYER_ENC0_RES_CONV2 = {
    .weightOffset = 14336,
    .weightSize   = 9216,
    .scaleOffset  = 23552,
    .scaleSize    = 128,
    .biasOffset   = 23680,
    .biasSize     = 128,
    .outChannels  = 32,
    .inChannels   = 32
};

// Layer: downsample_1
inline constexpr LayerDescriptor LAYER_DOWNSAMPLE_1 = {
    .weightOffset = 23808,
    .weightSize   = 18432,
    .scaleOffset  = 42240,
    .scaleSize    = 256,
    .biasOffset   = 42496,
    .biasSize     = 256,
    .outChannels  = 64,
    .inChannels   = 32
};

// Layer: enc1_res_conv1
inline constexpr LayerDescriptor LAYER_ENC1_RES_CONV1 = {
    .weightOffset = 42752,
    .weightSize   = 36864,
    .scaleOffset  = 79616,
    .scaleSize    = 256,
    .biasOffset   = 79872,
    .biasSize     = 256,
    .outChannels  = 64,
    .inChannels   = 64
};

// Layer: enc1_res_conv2
inline constexpr LayerDescriptor LAYER_ENC1_RES_CONV2 = {
    .weightOffset = 80128,
    .weightSize   = 36864,
    .scaleOffset  = 116992,
    .scaleSize    = 256,
    .biasOffset   = 117248,
    .biasSize     = 256,
    .outChannels  = 64,
    .inChannels   = 64
};

// Layer: conv_gru_conv_rz
inline constexpr LayerDescriptor LAYER_CONV_GRU_CONV_RZ = {
    .weightOffset = 117504,
    .weightSize   = 147456,
    .scaleOffset  = 264960,
    .scaleSize    = 512,
    .biasOffset   = 265472,
    .biasSize     = 512,
    .outChannels  = 128,
    .inChannels   = 128
};

// Layer: conv_gru_conv_h
inline constexpr LayerDescriptor LAYER_CONV_GRU_CONV_H = {
    .weightOffset = 265984,
    .weightSize   = 73728,
    .scaleOffset  = 339712,
    .scaleSize    = 256,
    .biasOffset   = 339968,
    .biasSize     = 256,
    .outChannels  = 64,
    .inChannels   = 128
};

// Layer: dec1_res_conv1
inline constexpr LayerDescriptor LAYER_DEC1_RES_CONV1 = {
    .weightOffset = 340224,
    .weightSize   = 36864,
    .scaleOffset  = 377088,
    .scaleSize    = 256,
    .biasOffset   = 377344,
    .biasSize     = 256,
    .outChannels  = 64,
    .inChannels   = 64
};

// Layer: dec1_res_conv2
inline constexpr LayerDescriptor LAYER_DEC1_RES_CONV2 = {
    .weightOffset = 377600,
    .weightSize   = 36864,
    .scaleOffset  = 414464,
    .scaleSize    = 256,
    .biasOffset   = 414720,
    .biasSize     = 256,
    .outChannels  = 64,
    .inChannels   = 64
};

// Layer: upsample_1
inline constexpr LayerDescriptor LAYER_UPSAMPLE_1 = {
    .weightOffset = 414976,
    .weightSize   = 18432,
    .scaleOffset  = 433408,
    .scaleSize    = 128,
    .biasOffset   = 433536,
    .biasSize     = 128,
    .outChannels  = 32,
    .inChannels   = 64
};

// Layer: skip_blend
inline constexpr LayerDescriptor LAYER_SKIP_BLEND = {
    .weightOffset = 433664,
    .weightSize   = 2048,
    .scaleOffset  = 435712,
    .scaleSize    = 128,
    .biasOffset   = 435840,
    .biasSize     = 128,
    .outChannels  = 32,
    .inChannels   = 64
};

// Layer: dec0_res_conv1
inline constexpr LayerDescriptor LAYER_DEC0_RES_CONV1 = {
    .weightOffset = 435968,
    .weightSize   = 9216,
    .scaleOffset  = 445184,
    .scaleSize    = 128,
    .biasOffset   = 445312,
    .biasSize     = 128,
    .outChannels  = 32,
    .inChannels   = 32
};

// Layer: dec0_res_conv2
inline constexpr LayerDescriptor LAYER_DEC0_RES_CONV2 = {
    .weightOffset = 445440,
    .weightSize   = 9216,
    .scaleOffset  = 454656,
    .scaleSize    = 128,
    .biasOffset   = 454784,
    .biasSize     = 128,
    .outChannels  = 32,
    .inChannels   = 32
};

// Layer: upscaler_up_conv
inline constexpr LayerDescriptor LAYER_UPSCALER_UP_CONV = {
    .weightOffset = 454912,
    .weightSize   = 36864,
    .scaleOffset  = 491776,
    .scaleSize    = 512,
    .biasOffset   = 492288,
    .biasSize     = 512,
    .outChannels  = 128,
    .inChannels   = 32
};

// Layer: upscaler_refine_0
inline constexpr LayerDescriptor LAYER_UPSCALER_REFINE_0 = {
    .weightOffset = 492800,
    .weightSize   = 9216,
    .scaleOffset  = 502016,
    .scaleSize    = 128,
    .biasOffset   = 502144,
    .biasSize     = 128,
    .outChannels  = 32,
    .inChannels   = 32
};

// Layer: upscaler_refine_2
inline constexpr LayerDescriptor LAYER_UPSCALER_REFINE_2 = {
    .weightOffset = 502272,
    .weightSize   = 9216,
    .scaleOffset  = 511488,
    .scaleSize    = 128,
    .biasOffset   = 511616,
    .biasSize     = 128,
    .outChannels  = 32,
    .inChannels   = 32
};

// Layer: upscaler_refine_4
inline constexpr LayerDescriptor LAYER_UPSCALER_REFINE_4 = {
    .weightOffset = 511744,
    .weightSize   = 1728,
    .scaleOffset  = 513472,
    .scaleSize    = 24,
    .biasOffset   = 513504,
    .biasSize     = 24,
    .outChannels  = 6,
    .inChannels   = 32
};

// Layer: upscaler_native_conv_0
inline constexpr LayerDescriptor LAYER_UPSCALER_NATIVE_CONV_0 = {
    .weightOffset = 513536,
    .weightSize   = 9216,
    .scaleOffset  = 522752,
    .scaleSize    = 128,
    .biasOffset   = 522880,
    .biasSize     = 128,
    .outChannels  = 32,
    .inChannels   = 32
};

// Layer: upscaler_native_conv_2
inline constexpr LayerDescriptor LAYER_UPSCALER_NATIVE_CONV_2 = {
    .weightOffset = 523008,
    .weightSize   = 1728,
    .scaleOffset  = 524736,
    .scaleSize    = 24,
    .biasOffset   = 524768,
    .biasSize     = 24,
    .outChannels  = 6,
    .inChannels   = 32
};

} // namespace upways
